app/controllers/users.controller.js, app/routes/user.routes.js, app/utils/utils.js, config/default.json
LoginRoute & RegisterRoute Completed.
**GIF**
=> feat: Add loginRoute & registerRoute

.gitignore, app/controllers/users.controller.js, app/models/user.model.js, config/default.json, package-lock.json, package.json
* JWT Token Auth implemented.
**GIF**
=> feat: Added JWT implementation

app/controllers/users.controller.js
**changes**
- sends generated token from jwt in the response cookie while login.
=> feat: send token in response cookie

app/controllers/product.controller.js, app/routes/product.routes.js, index.js
**changes**
- added CRUD operation for product
> need to change image type in DB schema while adding or updating the product
=> feat: product route and controller

app/controllers/auth.controller.js, app/controllers/product.controller.js, app/controllers/users.controller.js, app/middleWare/auth.js, app/models/product.model.js, app/models/user.model.js, app/routes/auth.routes.js, app/routes/product.routes.js, app/routes/user.routes.js, app/utils/utils.js, config/default.json, index.js
Below of the Task are implemented in the PR.
It takes all the data and add the data in the DB for any user(normal/admin).
It shows all product for the admin user and corresponding products for the other user.
=> feat: Add CRUD for Admin Page

index.js, middleware/auth.js, package-lock.json, package.json, views/dashboard.ejs, views/layouts/full-width.ejs, views/layouts/loginLayout.ejs, views/login.ejs, views/partials/footer.ejs, views/partials/header.ejs, views/product.ejs
**changes**
- Setup ejs for Admin panel
- Create login ui for admin
- Create Dashboard UI
**Login**
**Dashboard**
=> Add UI for Admin panel

index.js, views/product.ejs
**Changes**
- add new product functionality in the admin panel
https://www.loom.com/share/3e3d2fa10b4f4cc6815a026e4d90964b
=> feat: add product functionality

config/default.json, index.js
Local and URL env variable fixed
=> fix: URL fixed

index.js, package-lock.json, package.json, views/product.ejs
**changes**
- added product delete functionality by id
https://www.loom.com/share/e653c0abdc3c45b09b600346875ca371
=> feat : Product delete 

index.js, views/layouts/full-width.ejs, views/product.ejs, views/productUpdate.ejs
- product update functionality added
=> feat: product update

app/controllers/orderController.js, app/dashboard/orderDashboard.js, app/models/order.model.js, app/routes/order.routes.js, index.js, test.html, views/orders.ejs, views/partials/header.ejs, views/productUpdate.ejs
* Adding of order and getting all orders.
* Order Display page
=> feat: add OrderDashboard

app/controllers/orderController.js
**changes**
- fix typo in orderController.js 
```diff
- const Order = require("../models/Order.model");
+ const Order = require("../models/order.model");
```
=> fix (order): model typo

app/controllers/orderController.js, app/dashboard/orderDashboard.js, app/models/order.model.js, app/routes/order.routes.js
* Added routes/controller for mostOrdered Product
* Users count route/controller added on the basis of daily, monthly and yearly.
=> feat: Added routes for Order DashBoard

app/dashboard/orderDashboard.js, views/orders.ejs
**changes**
- added chart on order page
=> feat: add chart in order ui

app/controllers/orderController.js, app/dashboard/orderDashboard.js, app/routes/order.routes.js, index.js, views/layouts/loginLayout.ejs, views/orderSummery.ejs, views/orders.ejs
**changes**
- added chart for
- Most ordered
- Order by Day/ Month/ Year
=> feat: add order by day/month/year in order chart

views/dashboard.ejs, views/product.ejs
**changes**
- add onError property on the image when img source is null
| before | after|
|-----|-----|
|![Screenshot from 2021-04-07 23-08-14](https://user-images.githubusercontent.com/20131952/113910695-c2bf5480-97f6-11eb-93d7-cdb0acaf471f.png) |![Screenshot from 2021-04-07 23-07-54](https://user-images.githubusercontent.com/20131952/113910728-ca7ef900-97f6-11eb-8311-f87140a3696d.png)|
=> fix:  image null  property

index.js, views/dashboard.ejs
**changes**
- add monthly graph
- add recent order table
=> fix: dashboard ui

app/dashboard/orderDashboard.js, views/dashboard.ejs, views/orders.ejs
**changes**
- remove " \' " from the title of the product
=> fix: bar chart on order page

app/dashboard/orderDashboard.js, views/dashboard.ejs
**changes**
``` dif
-const { token } = "req.cookies;";
+const { token } = req.cookies;
```
=> fix: order summery

views/dashboard.ejs
=> fix: Most Ordered Display

config/default.json, index.js, package-lock.json, package.json
**changes**
- added Razorpay for payment in the backend to handle order
=> feat: added razorpay for payment

app/dashboard/orderDashboard.js, index.js, views/dashboard.ejs, views/orderSummery.ejs, views/product.ejs
**changes**
- fix typos in the order summary
- fix UI of the product table
- fix dashboard UI
| before | after|
|-----|-----|
|![Screenshot from 2021-04-12 17-58-09](https://user-images.githubusercontent.com/20131952/114394302-ad607680-9bb8-11eb-865f-43bdf4cf00d8.png)|![Screenshot from 2021-04-12 17-57-06](https://user-images.githubusercontent.com/20131952/114394250-9e79c400-9bb8-11eb-82d9-684972b96ecc.png)|
=> fix: typo and ui

app/controllers/product.controller.js, app/dashboard/orderDashboard.js, app/routes/product.routes.js
**changes**
- remove auth for product listing.
=> fix: remove auth for product listing
